package core

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"vigil/internal/artifacts"
	"vigil/internal/store"
)

type ExportedArtifact struct {
	ID     string `json:"id"`
	Digest string `json:"digest"`
	Kind   string `json:"kind"`
	Path   string `json:"path"`
}

type ExportedURL struct {
	DeliveryID string `json:"delivery_id"`
	URL        string `json:"url"`
}

type ArchiveExport struct {
	SchemaVersion int                `json:"schema_version"`
	PlanID        string             `json:"plan_id"`
	Revision      int                `json:"revision"`
	Manifest      string             `json:"manifest"`
	Narrative     string             `json:"narrative,omitempty"`
	Artifacts     []ExportedArtifact `json:"artifacts"`
	ExternalURLs  []ExportedURL      `json:"external_urls"`
}

// ExportArchive creates a new, private, self-contained directory. Every file
// name is generated by Vigil; artifact IDs and digests are verified before any
// byte is written. A failed export leaves a visibly incomplete directory with
// no export-index.json, rather than overwriting an existing user directory.
func (e *Engine) ExportArchive(ctx context.Context, planID string, revision int, destination string) (ArchiveExport, error) {
	result := ArchiveExport{SchemaVersion: 1, PlanID: planID, Revision: revision, Manifest: "manifest.json", Artifacts: []ExportedArtifact{}, ExternalURLs: []ExportedURL{}}
	record, manifest, err := e.Archive(ctx, planID, revision)
	if err != nil {
		return result, err
	}
	repository, err := artifacts.New(e.DB)
	if err != nil {
		return result, err
	}
	manifestBytes, err := repository.Read(ctx, record.ManifestID)
	if err != nil {
		return result, err
	}
	var narrativeBytes []byte
	if record.NarrativeID != "" {
		narrativeBytes, err = repository.Read(ctx, record.NarrativeID)
		if err != nil {
			return result, err
		}
		result.Narrative = "narrative.json"
	}
	for _, delivery := range manifest.Deliveries {
		if delivery.URL == "" {
			continue
		}
		// Same rule as the archive collector: https, or the credential-free
		// loopback host used only by marked disposable fixtures.
		parsed, err := url.Parse(delivery.URL)
		if err != nil || parsed.User != nil || parsed.Host == "" ||
			(parsed.Scheme != "https" && !fixtureLoopback(parsed.Scheme+"://"+parsed.Host)) {
			return result, errors.New("archive contains an invalid or credential-bearing external URL")
		}
		result.ExternalURLs = append(result.ExternalURLs, ExportedURL{DeliveryID: delivery.ID, URL: delivery.URL})
	}
	parent, name, err := safeExportParent(destination)
	if err != nil {
		return result, err
	}
	defer parent.Close()
	if err := parent.Mkdir(name, 0700); err != nil {
		return result, fmt.Errorf("export destination must not already exist: %w", err)
	}
	created, err := parent.Lstat(name)
	if err != nil || !created.IsDir() || created.Mode()&os.ModeSymlink != 0 {
		return result, errors.New("export directory changed after creation")
	}
	root, err := parent.OpenRoot(name)
	if err != nil {
		return result, err
	}
	defer root.Close()
	opened, err := root.Stat(".")
	if err != nil || !os.SameFile(created, opened) {
		return result, errors.New("export directory changed while opening")
	}
	if err := writeExportFile(root, "manifest.json", manifestBytes); err != nil {
		return result, err
	}
	if len(narrativeBytes) != 0 {
		if err := writeExportFile(root, "narrative.json", narrativeBytes); err != nil {
			return result, err
		}
	}
	if err := root.Mkdir("artifacts", 0700); err != nil {
		return result, err
	}
	written := map[string]bool{}
	for _, ref := range manifest.Artifacts {
		if !store.SafeID(ref.ID) || !validDigest(ref.Digest) {
			return result, errors.New("archive contains an invalid artifact reference")
		}
		content, err := repository.Read(ctx, ref.ID)
		if err != nil || store.Digest(content) != ref.Digest {
			return result, fmt.Errorf("archive artifact %s is missing or corrupt", ref.ID)
		}
		path := "artifacts/" + ref.Digest
		if !written[ref.Digest] {
			if err := writeExportFile(root, path, content); err != nil {
				return result, err
			}
			written[ref.Digest] = true
		}
		result.Artifacts = append(result.Artifacts, ExportedArtifact{ID: ref.ID, Digest: ref.Digest, Kind: ref.Kind, Path: path})
	}
	index, err := json.Marshal(result)
	if err != nil {
		return result, err
	}
	if err := writeExportFile(root, "export-index.json", index); err != nil {
		return result, err
	}
	return result, nil
}

func writeExportFile(root *os.Root, path string, content []byte) error {
	f, err := root.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	_, writeErr := f.Write(content)
	if writeErr == nil {
		writeErr = f.Sync()
	}
	closeErr := f.Close()
	if writeErr != nil {
		return writeErr
	}
	return closeErr
}

func safeExportParent(destination string) (*os.Root, string, error) {
	if !filepath.IsAbs(destination) || strings.ContainsRune(destination, 0) || destination != filepath.Clean(destination) {
		return nil, "", errors.New("export requires an absolute canonical destination")
	}
	parentPath, name := filepath.Dir(destination), filepath.Base(destination)
	if name == "." || name == string(filepath.Separator) || name == ".." {
		return nil, "", errors.New("export destination must be a new named directory")
	}
	// The directory the operator named must itself be a real directory, not a
	// symbolic link: an alias there is the redirection this check exists to
	// refuse. Ancestors above it are deliberately NOT rejected, because system
	// roots are legitimately symbolic links on some platforms (macOS resolves
	// /var and /tmp through /private), and those are the OS's own layout rather
	// than anything the operator controls. os.OpenRoot then confines every
	// subsequent operation to the resolved parent, so an ancestor symlink cannot
	// redirect the export once this point is passed.
	info, err := os.Lstat(parentPath)
	if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return nil, "", errors.New("export parent must be an existing real directory, not a symbolic link")
	}
	before := info
	root, err := os.OpenRoot(parentPath)
	if err != nil {
		return nil, "", err
	}
	after, err := root.Stat(".")
	if err != nil || !os.SameFile(before, after) {
		root.Close()
		return nil, "", errors.New("export parent changed while opening")
	}
	return root, name, nil
}
